theme = "awesome-identity"
baseURL = ""
title = "BeYoung"


## Profile Configurations
[params.profile]
  portrait = "/images/pic.jpg"
  firstname = "Benson"
  lastname = "Yeung"
  title = "Student at UofT / Data Analyst"
  bio = """I like to eat duh rice
  """


## Footer Configurations
[params.footer]
  copyright = "© 2019 Benson Yeung. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true
